# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('idActivity', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('happening', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, default='')),
                ('outcomes', models.CharField(max_length=2000)),
                ('funding', models.CharField(max_length=500)),
                ('reviewed', models.CharField(max_length=100)),
                ('unitNotes', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('idActivityType', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPartner',
            fields=[
                ('idCommunityPartner', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('activities', models.ManyToManyField(to='activity_finder.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('idCourse', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('activities', models.ManyToManyField(to='activity_finder.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('idFocusArea', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('activities', models.ManyToManyField(to='activity_finder.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('idLocation', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('activities', models.ManyToManyField(to='activity_finder.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('idPeople', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('idPopulation', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('activities', models.ManyToManyField(to='activity_finder.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('idSchool', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServedNeighbourhood',
            fields=[
                ('idServedNeighbourhood', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('activities', models.ManyToManyField(to='activity_finder.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('idUnit', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('activities', models.ManyToManyField(to='activity_finder.Activity')),
                ('idSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_finder.School')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='idActivityType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_finder.ActivityType'),
        ),
        migrations.AddField(
            model_name='activity',
            name='idPeople',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_charge_person', to='activity_finder.People'),
        ),
        migrations.AddField(
            model_name='activity',
            name='universityLeaders',
            field=models.ManyToManyField(related_name='university_leader', to='activity_finder.People'),
        ),
    ]
