# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='idActivityType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_finder.ActivityType'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
