# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='activity',
            name='outcomes',
            field=models.TextField(max_length=2000),
        ),
    ]
