# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0002_auto_20170607_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
