# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0002_auto_20170616_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='funding',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='outcomes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='reviewed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='unitNotes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
