# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0003_auto_20170616_1946'),
        ('activity_finder', '0003_auto_20170616_2159'),
    ]

    operations = [
    ]
