# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0003_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypartner',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='course',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='focusarea',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='location',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='population',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='servedneighbourhood',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='activities',
        ),
        migrations.AddField(
            model_name='activity',
            name='idCommunityPartner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_finder.CommunityPartner'),
        ),
        migrations.AddField(
            model_name='activity',
            name='idCourse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_finder.Course'),
        ),
        migrations.AddField(
            model_name='activity',
            name='idFocusArea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_finder.FocusArea'),
        ),
        migrations.AddField(
            model_name='activity',
            name='idLocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_finder.Location'),
        ),
        migrations.AddField(
            model_name='activity',
            name='idPopulation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_finder.Population'),
        ),
        migrations.AddField(
            model_name='activity',
            name='idServedNeighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_finder.ServedNeighbourhood'),
        ),
        migrations.AddField(
            model_name='activity',
            name='idUnit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_finder.Unit'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='idPeople',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_charge_person', to='activity_finder.People'),
        ),
    ]
