# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0003_auto_20170616_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='servedNeighbourhoods',
        ),
        migrations.AddField(
            model_name='activity',
            name='servedneighbourhoods',
            field=models.ManyToManyField(to='activity_finder.ServedNeighbourhood'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='communityPartners',
            field=models.ManyToManyField(to='activity_finder.CommunityPartner'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='courses',
            field=models.ManyToManyField(to='activity_finder.Course'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='focusAreas',
            field=models.ManyToManyField(to='activity_finder.FocusArea'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='locations',
            field=models.ManyToManyField(to='activity_finder.Location'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='populations',
            field=models.ManyToManyField(to='activity_finder.Population'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='units',
            field=models.ManyToManyField(to='activity_finder.Unit'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='universityLeaders',
            field=models.ManyToManyField(to='activity_finder.People'),
        ),
    ]
