# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0004_auto_20170623_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='communityPartners',
            new_name='communitypartners',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='focusAreas',
            new_name='focusareas',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='universityLeaders',
            new_name='universityleaders',
        ),
    ]
