# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0005_auto_20170623_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='idActivityType',
            new_name='activitytype',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='idPeople',
            new_name='people',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='idSchool',
            new_name='school',
        ),
    ]
