# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0011_auto_20170626_1237'),
        ('activity_finder', '0004_merge_20170617_1439'),
    ]

    operations = [
    ]
