# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 12:15
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0012_merge_20170626_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='position',
            field=geoposition.fields.GeopositionField(default=(40.444269, -79.95326), max_length=42),
            preserve_default=False,
        ),
    ]
