# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0013_location_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
