# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0015_auto_20170731_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='schools',
            field=models.ManyToManyField(to='activity_finder.School'),
        ),
    ]
