# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0018_auto_20170814_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activitytype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_type', to='activity_finder.ActivityType'),
        ),
    ]
