# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0019_auto_20170814_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('idType', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='act_type', to='activity_finder.Type'),
        ),
    ]
