# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0020_auto_20170814_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='type',
            new_name='activity_type',
        ),
    ]
