# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0021_auto_20170814_2126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Activity_Type',
        ),
    ]
