# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0022_auto_20170814_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.DeleteModel(
            name='Activity_Type',
        ),
    ]
