# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0023_auto_20170814_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activitytype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_finder.ActivityType'),
        ),
    ]
