# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0024_auto_20170815_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='school',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='units',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
