# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0025_auto_20170830_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='servedneighbourhoods',
        ),
        migrations.DeleteModel(
            name='ServedNeighbourhood',
        ),
    ]
