# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0030_auto_20170830_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='type',
            field=models.CharField(max_length=45),
        ),
    ]
