# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0031_auto_20170830_2134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
