# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0033_auto_20170830_2137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='PeopleType',
        ),
    ]
