# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0035_auto_20170830_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_finder.PeopleType'),
        ),
    ]
