# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0036_auto_20170830_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='phone_number',
            field=models.CharField(default=11, max_length=20),
            preserve_default=False,
        ),
    ]
