# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0037_people_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Population',
            new_name='PopulationServed',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='populations',
            new_name='populations_served',
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='website_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='activity_finder.Course'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='schools',
            field=models.ManyToManyField(blank=True, null=True, to='activity_finder.School'),
        ),
    ]
