# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0038_auto_20170830_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='reviewed',
            field=models.BooleanField(),
        ),
    ]
