# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0041_auto_20170830_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
