# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0043_remove_activity_happening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='outcomes',
            field=models.TextField(blank=True, help_text='Unique identifier for the student', max_length=2000, null=True),
        ),
    ]
