# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 14:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0044_auto_20170831_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_date',
        ),
        migrations.AddField(
            model_name='activity',
            name='estimated_end_date',
            field=models.DateField(blank=True, help_text='(yyyy-mm-dd). Leave blank if currently ongoing.', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='estimated_start_date',
            field=models.DateField(default=datetime.date.today, help_text='(yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='funding',
            field=models.CharField(blank=True, help_text='Please include the internal (Pitt) and external sources of funding that support this activity.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='outcomes',
            field=models.TextField(blank=True, help_text='Please include a description of any products, programs, or outputs this activity has generated.', max_length=2000, null=True),
        ),
    ]
