# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_finder', '0045_auto_20170831_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='contactInformation',
            field=models.BooleanField(help_text='Please check it if you want the contact information to be visible in public.'),
        ),
    ]
